version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend/src:/app/src
    environment:
      - NODE_ENV=production
      - DATABASE_URL=your_database_url_here
    depends_on:
      - db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./admin/src:/app/src

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database_name
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: